export const REQUEST_SCHEDULE = "REQUEST_SCHEDULE"
export const SAVE_SCHEDULE = "SAVE_SCHEDULE"

export const LOAD_GAME = "LOAD_GAME"
export const SAVE_PROBABLE_STARTERS = "SAVE_PROBABLE_STARTERS"
export const SAVE_BVP_DATA = "SAVE_BVP_DATA"